feat(default-theme): Add pagination for placed orders
vuestorefront/shopware-pwa pull request #1897
Opened 2022-06-09 10:12 UTC by quando1910

## Changes
This PR closes https://github.com/vuestorefront/shopware-pwa/issues/379

### Checklist
- [ ] Pagination component is visible on orders history page
- [ ] default pagination params are consistent with the default settings (10 per page)
- [ ] consider: do not show pagination if orders collection is less than 11

2022-06-10 11:35 UTC, mkucmus commented on packages/composables/__tests__/useCustomerOrders.spec.ts
> +    describe("getTotal", () => {
great one!

2022-06-10 11:37 UTC, mkucmus approved these changes
🚀 that's what pagination should look like 💪🏻

2022-06-13 12:47 UTC, patzick requested changes
The code looks very good. Well done. 
Although we have two issues I spotted. The first one is that going to Account -> Order history is sending three post requests. Please investigate why is this happening 
<img width="438" alt="image" src="https://user-images.githubusercontent.com/13100280/173356509-2292c1af-30ba-4a4f-a05c-18e2755514be.png">


The other issue is that we're displaying "0" as number of order history
<img width="551" alt="image" src="https://user-images.githubusercontent.com/13100280/173356611-f6758f6e-d73e-464a-a1d2-9839c04b6d39.png">


A probable solution for both problems would be using `sharedRef` to share elements between multiple instances of a composable.

2022-06-14 04:34 UTC, quando1910 commented
@patzick 
this is because we repeat `nuxt-child` 3 times. Each time the route changes, the current page will be rendered 3 times, but only show 1, the remaining pages are hidden. 
I can solve this problem by the below solution. How do you think ?
<img width="1340" alt="Screen Shot 2022-06-14 at 11 30 13 AM" src="https://user-images.githubusercontent.com/29194019/173493735-b904e1e7-3643-4de3-879d-7621aa118110.png">

2022-06-14 10:38 UTC, patzick approved these changes
👌

2022-06-14 10:38 UTC, merged