[WIP] feat(default-theme): Add newsletter subscription
vuestorefront/shopware-pwa pull request #1928
Opened 2022-08-03 16:08 UTC by mdanilowicz

Work on this PR will be continued after backend fixes

## Changes
closes #1756

### Checklist

- [ ] the [list of features](docs/guide/FEATURELIST.md) is updated (if it's a feature and it's relevant)
- [ ] I followed [contributing](https://github.com/DivanteLtd/shopware-pwa/blob/master/CONTRIBUTING.md) guidelines

2022-08-04 12:08 UTC, patzick requested changes
Very nice, just one thing to improve with form data model :)

2022-08-04 12:08 UTC, patzick commented on packages/default-theme/src/components/account/SwNewsletter.vue
> +        v-model="user.email"
we shouldn't modify the user's email here, for form purposes we can add prefilled ref, for example
```ts
const userEmail = ref(user.value?.email);
```

2022-08-04 12:08 UTC, patzick commented on packages/default-theme/src/components/account/SwNewsletter.vue
> +import { useUser, useNotifications } from "@shopware-pwa/composables"
```suggestion
import { getApplicationContext, useUser, useNotifications } from "@shopware-pwa/composables"
```

2022-08-29 07:59 UTC, mkucmus commented
@mdanilowicz  do we have an issue which blocks us here to link between repositories? available maybe here: https://issues.shopware.com

2024-10-31 15:12 UTC, closed without merging